name: Python package

on: [push]

jobs:
  test_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pipenv"
      - run: pipenv sync --dev
      - name: Lint
        run: |
          ./x.py lint
      - name: Test
        run: |
          ./x.py test --coverage
